config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
 get 'prix', to: 'frontend/pages#price', as: 'price'

 get 'maps', to: 'frontend/pages#maps', as: 'maps'
 get 'app', to: 'frontend/pages#maps', as: 'app'
 get 'shop', to: 'frontend/shop#index', as: 'shop'
 get 'shop/products/:id', to: "frontend/shop#show", as: 'shop_product'
 get 'order', to: "frontend/shop#order" , as: 'order_path'
 post 'confirm_order', to: 'frontend/shop#confirm_order'
 get 'thanks', to: 'frontend/shop#thanks'

  
  namespace :frontend do 
    resources :contacts
  end

  namespace :backend do
    resources :contacts
    resources :interventions
    resources :customers
    resources :beboxs 
    resources :parts
    resources :maintenances
    resources :products
    resources :visits
    resources :users
    get "maintenances/note", to: "maintenances#note", as: "note"
    get "maintenances/new2", to: "maintenances#new2"
  end

  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "frontend#index"
    get "admin", to: "backend#index", as: "admin"
    get "management", to: "backend#index", as: "user_root"
    get "backend/inventory", to: "backend#inventory", as: "inventory"
    post "edit_user", to: "backend/users#check_pw", as: "edit_user"
    get 'test', to: 'frontend#test', as: 'test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bebox.rb
class Bebox < ApplicationRecord
  belongs_to :customer
  has_many :maintenances

   enum category: [:Be_Elegant, :Be_Cube]
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :beboxes
end

app/models/intervention.rb
class Intervention < ApplicationRecord
  belongs_to :part
  belongs_to :maintenance
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
    belongs_to :bebox
    has_many :interventions,  dependent: :destroy

    enum category: [:telephone, :intervention]
end

app/models/part.rb
class Part < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum function: [:default, :admin, :commercial, :maintenance]
end

app/models/visit.rb
class Visit < ApplicationRecord
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
	layout "backend"
    #http_basic_authenticate_with name: "info@mybebox.tn", password: "beboxkey"
    before_action :authenticate_user!

	def index
        @maintenances= Maintenance.where(todo: "1").all
    	@tocall = []
    	beboxes = Bebox.all
    	beboxes.each do |bebox|
    		t = Time.now - 720.hours  
    		puts t
    		if bebox.maintenances.last.present?
	    		if t > bebox.maintenances.last.created_at
	    			@tocall.push(bebox) 
	    		end
            else
                if t > bebox.created_at
                    @tocall.push(bebox)
                end
    		end
    	end
	end
    
    
    def ineventory
    end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
    layout "frontend"
    
    def index
    	@contact = Contact.new 
    end
    
    def test
        @variable = Bebox.first
        render :json => @variable.location
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/parts_helper.rb
module Backend::PartsHelper
end

app/helpers/backend_helper.rb
module BackendHelper

  def bc_link(name, link = nil)
    content_tag :li, itemscope: 'itemscope', itemtype: 'http://data-vocabulary.org/Breadcrumb', class: (link ? nil : 'active') do
      if link
        link_to link, itemprop: 'url' do
          content_tag :span, itemprop: 'title' do
            name
          end
        end
      else
        content_tag :span, itemprop: 'title' do
          name
        end
      end
    end
  end
	
  def menu_active(c_name, second = true)
    return 'active' if controller_name == c_name && second
  end

end

app/helpers/beboxs_helper.rb
module BeboxsHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/maintenances_helper.rb
module MaintenancesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/admin/_navigation.html.erb
<div class="profile-box row">
  <div class="profile col-md-12">
    <%= image_tag "logo.png", class: "image", width: 50%>
    <div class="profile">
      <strong><%= current_user.name %></strong>
      <small><%= current_user.email %></small><br>
      <small> <%= link_to "Se deconnecter",  destroy_user_session_path, method: :delete %></small>
    </div>
    <% if Rails.env.staging? %>
      (STAGING)
    <% end %>
  </div>
</div>
<ul>
    <li><%= link_to "Tableau de bord", admin_path, class: "fa fa-pie-chart #{menu_active("backend", action_name == 'index')}" %></li>
    <% if current_user.function == 'admin' %>
      <li><%= link_to "Clients",  backend_customers_path, class: "fa fa-users #{menu_active("customers")}" %></li>
      <li><%= link_to "Beboxes",  backend_beboxs_path, class: "fa fa-th-large #{menu_active("beboxs")}" %></li>
      <li><%= link_to "Maintenances",  backend_maintenances_path, class: "fa fa-cog #{menu_active("maintenances")}" %></li>
      <li><%= link_to "Commercial",  backend_visits_path, class: "fa fa-briefcase #{menu_active("visits")}" %></li>
      <li><%= link_to "Inventaire", inventory_path, class: "fa fa-cubes #{menu_active("backend", action_name == 'inventory')}" %></li>
      <li><%= link_to "Contacts",  backend_contacts_path, class: "fa fa-user-plus #{menu_active("contacts")}" %></li>
      <li><%= link_to "Products",  backend_products_path, class: "fa fa-shopping-cart #{menu_active("products")}" %></li>
    <% end %>
    <% if current_user.function == 'commercial' %>
      <li><%= link_to "Commercial",  backend_visits_path, class: "fa fa-briefcase #{menu_active("visits")}" %></li>
    <% end %>
    <li><%= link_to "Admin Users",  backend_users_path, class: "fa fa-user-plus #{menu_active("users")}" %></li>
</ul>