config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
 get 'prix', to: 'frontend/pages#price', as: 'price'

 get 'maps', to: 'frontend/pages#maps', as: 'maps'
 get 'app', to: 'frontend/pages#maps', as: 'app'
 get 'shop', to: 'frontend/shop#index', as: 'shop'
 get 'shop/products/:id', to: "frontend/shop#show", as: 'shop_product'
 get 'order', to: "frontend/shop#order" , as: 'order_path'
 post 'confirm_order', to: 'frontend/shop#confirm_order'
 get 'thanks', to: 'frontend/shop#thanks'

  
  namespace :frontend do 
    resources :contacts
  end

  namespace :backend do
    resources :contacts
    resources :interventions
    resources :customers
    resources :beboxs 
    resources :parts
    resources :maintenances
    resources :products
    resources :visits
    resources :users
    get "maintenances/note", to: "maintenances#note", as: "note"
    get "maintenances/new2", to: "maintenances#new2"
  end

  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "frontend#index"
    get "admin", to: "backend#index", as: "admin"
    get "management", to: "backend#index", as: "user_root"
    get "backend/inventory", to: "backend#inventory", as: "inventory"
    post "edit_user", to: "backend/users#check_pw", as: "edit_user"
    get 'test', to: 'frontend#test', as: 'test'
end

app/models/bebox.rb
class Bebox < ApplicationRecord
  belongs_to :customer
  has_many :maintenances

   enum category: [:Be_Elegant, :Be_Cube]
end

app/controllers/backend/beboxs_controller.rb
class Backend::BeboxsController < BackendController
       
    def index
    	@bebox = Bebox.order(created_at: :desc)
    end
     
    def create
     @bebox = Bebox.new(bebox_params)
     if @bebox.save
        redirect_to  backend_beboxs_path ,notice: "bebox Ajouter"
     else
        
      redirect_to new_backend_bebox
        end 
    end


    def new
        @bebox = Bebox.new 
    end 
  
    def show
    	@bebox = Bebox.find(params[:id])
    end

    def edit
    	@bebox = Bebox.find(params[:id])
    end
    
    def edit_date
        @bebox = Bebox.find(params[:id])
    end

    def update
        @bebox = Bebox.find(params[:id])
        if @bebox.update(bebox_params)
            redirect_to backend_bebox_path(@bebox) ,notice: "Bebox mise a jour"
        end 
    end   

    def destroy
        @bebox = Bebox.find(params[:id])
        if @bebox.destroy
            redirect_to backend_beboxs_path ,notice: "Bebox supprime"
        else
            redirect_to bakend_bebox_controller(@bebox), notice: "problem! Bebox n'a pas ete suprrime"
        end
    end      

    def bebox_params
  		params.require(:bebox).permit(:reference, :location , :longitude , :laltitude , :category , :customer_id, :price, :created_at)
  	end
end

app/controllers/backend/contacts_controller.rb
class Backend::ContactsController < BackendController
  def index
  	@contacts = Contact.order(created_at: :desc)
  end
  def create
     @contacts = Contact.new(contact_params)
     if @contacts.save
        redirect_to  backend_contacts_path ,notice: "Contact Ajouter"
     else
        
      redirect_to new_backend_contact
        end 
    end
       def new
        @contacts = Contact.new 
    end 
    def show
    	@contacts = Contact.find(params[:id])
    end

    def edit
    	@contacts = Contact.find(params[:id])
    end

    
    def destroy
        @contacts = Contact.find(params[:id])
        if @contacts.destroy
            redirect_to backend_contacts_path ,notice: "Contact supprime"
        else
            redirect_to backend_contact_path(@contacts), notice: "problem! Contact n'a pas ete suprrime"
        end
    end      
    def contact_params
  		params.require(:contact).permit(:name, :surname , :company , :email , :Telephone ,:message)
  	end
end

app/controllers/backend/customers_controller.rb
class Backend::CustomersController < BackendController
	def index
		@customer = Customer.order(created_at: :desc)
	end
  def new
        @customer = Customer.new 
  end

  def create
     @customer = Customer.new(customer_params)
     if @customer.save
        redirect_to  backend_customers_path ,notice: "bebox Ajouter"
     else
        
      redirect_to new_backend_customer
        end 
    end 
  
	def show
		@customer = Customer.find(params[:id])
	end
	 def edit
     	@customer = Customer.find(params[:id])
     end
   def update
      @customer = Customer.find(params[:id])
      if @customer.update(customer_params)
      redirect_to backend_customers_path ,notice: "Customer mise a jour"
      end 
     end  
  def destroy
    @customer = Customer.find(params[:id])
    if @customer.destroy
      redirect_to backend_customers_path ,notice: "Customer supprime"
    else
      redirect_to bakend_customer_controller(@customer), notice: "problem! Customer n'a pas ete suprrime"
        end
  end      
  
     def customer_params
  		params.require(:customer).permit(:email, :name , :company , :phone)
  	end
end

app/controllers/backend/interventions_controller.rb
class Backend::InterventionsController < BackendController

	def new
		@maintenance = Maintenance.find(session[:maintenance])
		@intervention = Intervention.new
	end

	def create
		@intervention = Intervention.new(intervention_params)
		if @intervention.save
			redirect_to new_backend_intervention_path, notice: "Intervention ajoute"
		else 
			redirect_to new_backend_intervention_path, alert: "L'intervention n'a pas ete ajoute"
		end
	end
    
    def destroy
        intervention = Intervention.find(params[:id])
        maintenance = intervention.maintenance
        if intervention.destroy
          redirect_to backend_maintenance_path(maintenance) ,notice: "Intervention supprime"
        end
    end

  private   

  	def intervention_params
  		params.require(:intervention).permit(:action, :part_id , :maintenance_id)
  	end
end

app/controllers/backend/maintenances_controller.rb
class Backend::MaintenancesController < BackendController
    
  def new
  	@maintenances = Maintenance.new
    session[:last_id] = params[:last_id]
  end
    
  def index
  	@maintenances = Maintenance.order(created_at: :desc)

  end

  def create
     @maintenances = Maintenance.new(maintenances_params)
     last_id = session[:last_id]
     if @maintenances.save
         if last_id != nil
            last = Maintenance.find(last_id) 
            last.todo = 0
            last.save
         end
        if @maintenances.category == 'telephone'
          render 'note'
        else
          session[:maintenance] = @maintenances.id
          redirect_to new_backend_intervention_path(@maintenance)
       end
     else
        redirect_to backend_maintenances_path, alert: "Une erreur s'est produite, la maintenace n'a pas ete ajouter"
      end 
  end 

  def edit
  	@maintenances = Maintenance.find(params[:id])
  end

  def show
  	@maintenances = Maintenance.find(params[:id])
  end

  def destroy
    @maintenances = Maintenance.find(params[:id])
    if @maintenances.destroy
      redirect_to backend_maintenances_path ,notice: "Maintenances supprime"
    end
  end 

  def update
      maintenance = Maintenance.find(params[:id])
          if maintenance.update(maintenances_params)
              redirect_to backend_maintenance_path(maintenance) ,notice: "Maintenances mise a jour"
          end 
     end  

  def note(maintenance)
    @maintenances = maintenance
  end

  private   

  def maintenances_params
		params.require(:maintenance).permit(:category, :bebox_id , :note, :todo, :created_at, :price)
	end

end

app/controllers/backend/parts_controller.rb
class Backend::PartsController < BackendController
  def index
    @part = Part.all
  end

  def show
    @part = Part.find(params[:id])
  end

  def edit
    @part = Part.find(params[:id])
  end

  def destroy
    @part = Part.find(params[:id])
    if @part.destroy
      redirect_to backend_parts_path ,notice: "Part supprime"
    
        end
  end

  def new
    @part = Part.new
  end
  def create
    @part = Part.new(parts_params)
     if @part.save
        redirect_to  backend_parts_path ,notice: "Part Ajouter"
        else
      redirect_to new_backend_part
        end 
  end
  def update
      @part = Part.find(params[:id])
      if @part.update(parts_params)
      redirect_to backend_parts_path ,notice: "Part mise a jour"
      end 
     end  
          
  def parts_params
      params.require(:part).permit(:name)
    end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < BackendController
    def index
        @products = Product.order(created_at: :desc)
    end

    def new
        @product = Product.new 
    end 

    def create
        product = Product.new(product_params)
        if product.save
            redirect_to  backend_products_path ,notice: "Produit Ajouter"
        else
            redirect_to new_backend_product_path, alert: "Une erreur s'est produite veuillez reessayer"
        end 
    end

    def destroy
        product = Product.find(params[:id])
        if product.destroy
            redirect_to backend_products_path, notice: "Produit Supprime avec succes"
        else
            redirect_to backend_products_path, alert: "Une erreur s'est produite veuillez reessayer"
        end
    end

    private

    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < BackendController
    def index
        @users = User.all
    end 
    
    def show
        @user = User.find(params[:id])
    end 

    def check_pw
        user = User.find(params[:user_id])
        if params[:token] == 'beboxkey'
            redirect_to edit_backend_user_path(user)
        else
            redirect_to backend_user_path(user), alert: "Le mot de passe est incorrect"
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to backend_user_path(@user), notice: "Les donnees de l'utilisateur ont ete mise a jour"
        else
            redirect_to backend_user_path(user), alert: "Erreur! Veuillez reessayer"
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :function)
    end
end

app/controllers/backend/visits_controller.rb
class Backend::VisitsController < BackendController
	def index
		@visits = Visit.order(created_at: :desc)
	end

	def new
		@visit = Visit.new
	end
	
	def show
    	@visits = Visit.find(params[:id])
    end

	def create
		visit = Visit.new(visit_params)
		if visit.save
			redirect_to backend_visits_path, notice: 'Visite client a ete ajoutee'
		else
			render 'new', alert: "Une erreur s'est produite. Veuillez reessayer"
		end
	end

	def edit
		@visits = Visit.find(params[:id])
	end

	def update
      @visits = Visit.find(params[:id])
      if @visits.update(visit_params)
      	redirect_to backend_visit_path(@visits) ,notice: "visit client  mise a jour"
      else
        redirect_to backend_visit_path(@visits) , alert: " erreur veuillez ressayez"
      end 
    end 

    def destroy
    	@visits = Visit.find(params[:id])
   		if @visits.destroy
      		redirect_to backend_visits_path ,notice: "visit client supprime"
  		else
            redirect_to backend_visit_path(@visits) , alert:"erreur veuillez ressayez"  
        end
  end

	private

	def visit_params
  		params.require(:visit).permit(:customer_name, :telephone , :location , :report, :user_id)
  	end
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
	layout "backend"
    #http_basic_authenticate_with name: "info@mybebox.tn", password: "beboxkey"
    before_action :authenticate_user!

	def index
        @maintenances= Maintenance.where(todo: "1").all
    	@tocall = []
    	beboxes = Bebox.all
    	beboxes.each do |bebox|
    		t = Time.now - 720.hours  
    		puts t
    		if bebox.maintenances.last.present?
	    		if t > bebox.maintenances.last.created_at
	    			@tocall.push(bebox) 
	    		end
            else
                if t > bebox.created_at
                    @tocall.push(bebox)
                end
    		end
    	end
	end
    
    
    def ineventory
    end
end

app/helpers/backend/beboxs_helper.rb
module Backend::BeboxsHelper
end

app/helpers/backend/contacts_helper.rb
module Backend::ContactsHelper
end

app/helpers/backend/customers_helper.rb
module Backend::CustomersHelper
end

app/helpers/backend/interventions_helper.rb
module Backend::InterventionsHelper
end

app/helpers/backend/maintenances_helper.rb
module Backend::MaintenancesHelper
end

app/helpers/backend/parts_helper.rb
module Backend::PartsHelper
end

app/helpers/backend/products_helper.rb
module Backend::ProductsHelper
end

app/helpers/backend/users_helper.rb
module Backend::UsersHelper
end

app/helpers/backend/visits_helper.rb
module Backend::VisitsHelper
end

app/views/backend/beboxs/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Bebox <span class="badge"></span></h3>
    <% link_to icon("plus-circle"), new_backend_bebox_path, class:"btn" %>
  </div>
  <div class="panel-body">
    <div class="row container">
            <%= form_for(@bebox, :url => backend_beboxs_path, :html => { :class => "form-horizontal col-xs-12 col-sm-4 col-sm-offset-4"}) do |f| %>
            
                <div class="form-group">
                    <%= f.label :reference, class: "" %>
                    <%= f.text_field :reference, placeholder:"Reference" ,class: "form-control transparent",rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :location, class: "" %>
                    <%= f.text_field :location, placeholder:"Exp: Jobi bar Sousse", class: "form-control ", rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :longitude, class: "" %> (trouver les coordonnes sur <a href="http://maps.google.com" target="blank">Google maps</a>)
                    <%= f.text_field :longitude, placeholder:"longitude", class: "form-control ", rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :laltitude, class: "" %>
                    <%= f.text_field :laltitude, placeholder:"altitude", class: "form-control ", rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :category, class: "" %>
                    <%= f.select(:category, Bebox.categories.keys.to_a,{}, {:class => "form-control btn btn-default dropdown-toggle"})%>
                </div>
                <div class="form-group">
                    <%= f.label :customer_id, class: "" %>
                    <%= f.collection_select(:customer_id, Customer.all,:id, :name ,{}, {:class => "form-control btn btn-default dropdown-toggle"})%>
                </div>
                <div class="form-group">
                    <%= f.label :price %>
                    <%= f.text_field :price, placeholder:"prix", class: "form-control ", rows: 3, required: true %>
                </div>
                
                    <%= f.submit "Ajouter", class: "col-xs-8 col-xs-offset-2 btn btn-danger" %>
            <% end %>
        </div>
  </div>
</div>

app/views/backend/beboxs/edit.html.erb
<% content_for :pagename, "Beboxes" %>
<% content_for :breadcrumb do %>
  <%= bc_link "Home", admin_path %>
  <%= bc_link "Beboxes", backend_beboxs_path%>
  <%= bc_link @bebox.reference %>
  <%= bc_link "edit" %>
<% end %>




<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Bebox <span class="badge"></span></h3>
    <% link_to icon("plus-circle"), new_backend_bebox_path, class:"btn" %>
  </div>
  <div class="panel-body">
    <div class="row container">
            <%=form_for [:backend,@bebox] , :html => {class: 'form-horizontal col-xs-12 col-sm-4 col-sm-offset-4' } do |f| %>
            
                <div class="form-group">
                    <%= f.label :reference, class: "" %>
                    <%= f.text_field :reference, placeholder:"Reference" ,class: "form-control transparent",rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :location, class: "" %>
                    <%= f.text_field :location, placeholder:"Location", class: "form-control ", rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :longitude, class: "" %>
                    <%= f.text_field :longitude, placeholder:"longitude", class: "form-control ", rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :laltitude, class: "" %>
                    <%= f.text_field :laltitude, placeholder:"laltitude", class: "form-control ", rows: 3, required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :category, class: "" %>
                    <%= f.select(:category, Bebox.categories.keys.to_a,{}, {:class => "form-control btn btn-default dropdown-toggle"})%>
                </div>
                <div class="form-group">
                    <%= f.label :customer_id, class: "" %>
                    <%= f.collection_select(:customer_id, Customer.all,:id, :name ,{}, {:class => "form-control btn btn-default dropdown-toggle"})%>
                </div>
                <div class="form-group">
                    <%= f.label :price %>
                    <%= f.text_field :price, placeholder:"prix", class: "form-control ", rows: 3, required: true %>
                </div>
                    <%= f.submit "Modifier", class: "col-xs-8 col-xs-offset-2 btn btn-danger" %>
            <% end %>
        </div>
  </div>
</div>

app/views/backend/beboxs/index.html.erb
<% content_for :pagename, "Beboxes" %>
<% content_for :breadcrumb do %>
  <%= bc_link "Home", admin_path %>
  <%= bc_link "Beboxes" %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Beboxes <span class="badge"><%= @bebox.count %></span></h3>
    <% link_to icon("plus-circle"), new_backend_bebox_path, class:"btn" %>
     <%= link_to new_backend_bebox_path do %>      
        <i class="fa fa-plus-circle fa-2x trash " aria-hidden="true"></i>
      <% end -%>
  </div>
  <div class="panel-body">
    
  </div>

<div class="panel-body">
    <div class="table-responsive">
      <table class="table table-condensed table-bordered table-striped table-hover">
        <thead>
          <tr>    
            <th style="width:15%;">Reference</th>
            <th style="width:25%;">Location</th>
            <th style="width:15%;">Categorie</th>
            <th style="width:15%;">Client</th>
            <th style="width:15%;">Prix</th>
            <th style="width:15%;">Date</th>
          </tr>
        </thead>
        <tbody>
          <% @bebox.each do |bebox| %>
            <tr>
              <td><%= link_to bebox.reference, backend_bebox_path(bebox) %></td>
              <td><%= bebox.location %></td>
              <td><%= bebox.category %></td>
              <td>
                  <%= link_to backend_customer_path(bebox.customer) do %>
                    <%= bebox.customer.name %>
                  <% end %>
              </td>
              <td><%= bebox.price %></td>
              <td><%= bebox.created_at.strftime("%d / %m / %y") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/backend/beboxs/new.html.erb
<% content_for :pagename, "Beboxes" %>
<% content_for :breadcrumb do %>
  <%= bc_link "Home", admin_path %>
  <%= bc_link "Beboxes", backend_beboxs_path%>
  
  <%= bc_link "new" %>
<% end %>

<%= render 'form' , bebox: @bebox%>

app/views/backend/beboxs/show.html.erb
<% content_for :pagename, "Bebox show" %>
<% content_for :breadcrumb do %>
  <%= bc_link "Home", admin_path %>
  <%= bc_link "Beboxes", backend_beboxs_path%>
  <%= bc_link @bebox.reference %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Profile <%= @bebox.reference %><span class="badge"></span></h3>
      <%= link_to backend_bebox_path(@bebox) , method: :delete , data: {confirm: "etes vous sure?"} do %>
        <i class="fa fa-trash fa-2x trash" style="margin:5px;" aria-hidden="true"></i>
      <% end -%>
      <%= link_to  edit_backend_bebox_path(@bebox) do %>
        <i class="fa fa-pencil fa-2x pancel" aria-hidden="true" style="margin:5px;"></i>
      <%end%>
      <button class="fa fa-calendar fa-2x calender" aria-hidden="true" style="margin:5px;border:none;background-color:transparent;"  data-toggle="modal" data-target="#myModal" ></button>
  </div>
  
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Reference:</dt>
      <dd><%= @bebox.reference %></dd>
      <dt>Location:</dt>
      <dd><%= @bebox.location %></dd>
       <dt>longitude:</dt>
      <dd><%= @bebox.longitude %></dd>
       <dt>Altitude:</dt>
      <dd><%= @bebox.laltitude %></dd>
      <dt>Categorie:</dt>
      <dd><%= @bebox.category %></dd>
      <dt>Client:</dt>
      <dd><%= @bebox.customer.name %></dd>
      <dt>Date de vente:</dt>
      <dd><%= @bebox.created_at.strftime("%d / %m / %y") %></dd>
    </dl>
    <hr class="featurette-devider">
    <div class="panel-heading">
        <h3 class="panel-title">Historique des maintenances</h3>
        <%= link_to 'Ajouter une maintenance', new_backend_maintenance_path(bebox_id: @bebox.id), class: "btn btn-danger" %>
    </div>
    <table class="table">
        <thead>
            <th>Nr.</th>
            <th>Categorie</th>
            <th>Date</th>
        </thead>
        <tbody>
            <% @bebox.maintenances.each do |maintenance| %>
                <tr>
                    <td><%= maintenance.id %></td>
                    <td><%= maintenance.category %></td>
                    <td><%= maintenance.created_at.strftime("%d / %m / %y a %H : %M") %></td>
                </tr>
            <% end -%>
        </tbody>

    </table>
  </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog" style="margin-top:80px;">
  <div class="modal-dialog" style="z-index:10000;">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Changer la date de vente</h4>
      </div>
      <div class="modal-body">
         <%=form_for [:backend,@bebox] , :html => {class: 'form-horizontal', style: 'padding:25px;' } do |f| %>
                <div class="form-group">
                    <%= f.label :date, class: "" %>
                    <%= f.text_field :created_at ,class: "form-control transparent datepicker",rows: 3, required: true %>
                </div>
         
      </div>
      <div class="modal-footer">
          <%= f.submit "Modifier", class: "btn btn-default" %>
      </div>
        <% end %>
    </div>

  </div>
</div>

<style>
     *= require bootstrap-datepicker ;
</style>